[build]
builder = "DOCKERFILE"

[[services]]
name = "backend"
source = "backend"
startCommand = "npx prisma db push --skip-generate && node dist/index.js"

[[services]]
name = "frontend"
source = "frontend"
startCommand = "npm run preview"
